<?php
/**
 * Plugin Name:       AI Post Summary
 * Plugin URI:        https://wordpress.org/plugins/ai-post-summary/
 * Description:       Automatically generates AI-powered summaries for your blog posts using Google Gemini or OpenAI ChatGPT. Display summaries at the top of posts to improve reader engagement and SEO.
 * Version: 1.1.1
 * Requires at least: 5.0
 * Requires PHP:      7.4
 * Author:            Aung Hein Mynn
 * Author URI:        https://profiles.wordpress.org/aheinmynn/
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       ai-post-summary
 * Domain Path:       /languages
 *
 * AI Post Summary is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * AI Post Summary is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AI Post Summary. If not, see https://www.gnu.org/licenses/gpl-2.0.html.
 *
 * @package AIPostSummary
 * @version 1.1.0
 * @author  Aung Hein Mynn
 * @license GPL-2.0-or-later
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Define plugin constants
define('AI_POST_SUMMARY_VERSION', '1.1.0');
define('AI_POST_SUMMARY_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('AI_POST_SUMMARY_PLUGIN_URL', plugin_dir_url(__FILE__));
define('AI_POST_SUMMARY_PLUGIN_FILE', __FILE__);

// Include required files
require_once AI_POST_SUMMARY_PLUGIN_DIR . 'includes/admin-settings.php';
require_once AI_POST_SUMMARY_PLUGIN_DIR . 'includes/post-editor.php';
require_once AI_POST_SUMMARY_PLUGIN_DIR . 'includes/api-handler.php';
require_once AI_POST_SUMMARY_PLUGIN_DIR . 'includes/frontend-display.php';

// Activation hook
register_activation_hook(__FILE__, 'ai_post_summary_activate');

function ai_post_summary_activate() {
    // Set default options on activation
    $default_options = array(
        'ai_post_summary_global_enable' => false,
        'ai_post_summary_api_provider' => 'gemini',
        'ai_post_summary_api_key' => '',
        'ai_post_summary_char_count' => 200,
        'ai_post_summary_disclaimer' => 'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.',
    );
    
    add_option('ai_post_summary_settings', $default_options);
}

// Deactivation hook
register_deactivation_hook(__FILE__, 'ai_post_summary_deactivate');

function ai_post_summary_deactivate() {
    // Clean up temporary data if needed
    // Note: We don't delete user settings on deactivation
}

// Uninstall hook
register_uninstall_hook(__FILE__, 'ai_post_summary_uninstall');

function ai_post_summary_uninstall() {
    // Clean up all plugin data on uninstall
    delete_option('ai_post_summary_settings');
    
    // Remove all post meta
    delete_post_meta_by_key('_ai_post_summary_enabled');
    delete_post_meta_by_key('_ai_post_summary_content');
    delete_post_meta_by_key('_ai_post_summary_regenerate_flag');
}
