<?php
/**
 * Frontend display for AI Post Summary plugin
 *
 * @package AIPostSummary
 * @since   1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

add_filter('the_content', 'ai_post_summary_display_summary');

function ai_post_summary_display_summary($content) {
    // Only show on single posts and main query
    if (!is_single() || !is_main_query() || is_admin()) {
        return $content;
    }
    
    global $post;
    
    // Verify we have a valid post object
    if (!$post || !isset($post->ID)) {
        return $content;
    }
    
    $options = get_option('ai_post_summary_settings', array());
    $global_enabled = isset($options['ai_post_summary_global_enable']) ? $options['ai_post_summary_global_enable'] : false;
    $post_enabled = get_post_meta($post->ID, '_ai_post_summary_enabled', true);
    $summary = get_post_meta($post->ID, '_ai_post_summary_content', true);
    
    if (!$global_enabled || !$post_enabled || empty($summary)) {
        return $content;
    }
    
    // Get disclaimer text from settings
    $disclaimer = isset($options['ai_post_summary_disclaimer']) ? 
        $options['ai_post_summary_disclaimer'] : 
        'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    
    $summary_html = '<div class="gpt-summary-box">
        <h4 class="gpt-summary-title">' . esc_html__('AI Summary', 'ai-post-summary') . '</h4>
        <div class="gpt-summary-content">' . wp_kses_post($summary) . '</div>
        <div class="gpt-summary-disclaimer">
            <small>ℹ️ ' . esc_html($disclaimer) . '</small>
        </div>
    </div>';
    
    return $summary_html . $content;
}

// Add CSS for summary display
add_action('wp_head', 'ai_post_summary_frontend_css');

function ai_post_summary_frontend_css() {
    ?>
    <style>
    .gpt-summary-box {
        background: #f8f9fa;
        border: 1px solid #e9ecef;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 30px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .gpt-summary-title {
        margin: 0 0 15px 0;
        color: #495057;
        font-size: 18px;
        font-weight: 600;
        border-bottom: 2px solid #007cba;
        padding-bottom: 5px;
        display: inline-block;
    }
    
    .gpt-summary-content {
        color: #6c757d;
        line-height: 1.6;
        font-size: 16px;
        margin-bottom: 12px;
    }
    
    .gpt-summary-disclaimer {
        border-top: 1px solid #e9ecef;
        padding-top: 8px;
        margin-top: 8px;
    }
    
    .gpt-summary-disclaimer small {
        color: #999;
        font-size: 12px;
        font-style: italic;
        display: block;
    }
    </style>
    <?php
}

// Shortcode for manual placement
add_shortcode('ai_post_summary', 'ai_post_summary_shortcode');

function ai_post_summary_shortcode($atts) {
    global $post;
    $summary = get_post_meta($post->ID, '_ai_post_summary_content', true);
    
    if (empty($summary)) {
        return '';
    }
    
    // Get disclaimer text from settings
    $options = get_option('ai_post_summary_settings');
    $disclaimer = $options['ai_post_summary_disclaimer'] ?? 'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    
    return '<div class="gpt-summary-box">
        <h4 class="gpt-summary-title">AI Summary</h4>
        <div class="gpt-summary-content">' . wp_kses_post($summary) . '</div>
        <div class="gpt-summary-disclaimer">
            <small>ℹ️ ' . esc_html($disclaimer) . '</small>
        </div>
    </div>';
}
